apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeting-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: solairerove/greeting:0.0.1
        ports:
        - name: greeting-port
          containerPort: 8080
