apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
    ports:
    - port: 30001
      nodePort: 30001
      targetPort: greeting-port
      protocol: TCP
    selector:
        app: greeting
    type: NodePort
